language: python

python:
  - 3.6.5

install:
  - pip install -r requirements.txt

script:
  # - flake8
  - python -m unittest discover tests

notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
